stages:
  - build

compile LKM for latest Arch Linux kernel:
  image: archlinux/base:latest
  stage: build
  before_script:
    - pacman -Sy --noconfirm archlinux-keyring
    - pacman-key --init
    - pacman -Syu --noconfirm linux-headers base-devel
    - export MODULE_DIR=$(dirname /lib/modules/*/build)
  script:
    - make

compile LKM for Ubuntu Bionic:
  image: ubuntu:bionic
  stage: build
  before_script:
    - apt update
    - apt install -y linux-headers-generic build-essential libelf-dev
    - export MODULE_DIR=$(dirname /lib/modules/*/build)
  script:
    - make
