
stages:
  - build

compile LKM for latest Arch Linux kernel:
  image: registry.t4cc0.re/t4cc0re/archlinux:latest
  stage: build
  before_script:
    - pacman -Sy --noconfirm linux-headers base-devel
    - export KERNEL=$(pacman -Q linux-headers | awk '{print $2 "-ARCH"}' | sed 's/.arch/-arch/g')
  script:
    - make

compile LKM for Ubuntu Bionic:
  image: ubuntu:bionic
  stage: build
  before_script:
    - apt update
    - apt install -y linux-headers-generic build-essential
    - export MODULE_DIR=$(dirname /lib/modules/*/build)
  script:
    - make
