#!/usr/bin/env bash

set -e

error() {
  echo $* 1>&2
  return 1
}

if [ $UID -ne 0 ]; then
  echo "Run me as root" 1>&2
  exit 1
fi

if ! lsmod | grep -q escalator; then
  modprobe escalator || insmod $(dirname $0)/escalator.ko || error "Unable to load kernel module"
  echo "Kernel module loaded!"
fi

PID=${1:?"Please specify a process ID"}

[ -d /proc/$PID ] || error "Refusing to patch root process"

UID_STRING=$(grep Uid: /proc/$PID/status)
PROC_UID=$(echo "$UID_STRING" | awk '{print $2}')


[ $PROC_UID -eq 0 ] && error "Refusing to patch root process"

echo $PID > /sys/kernel/escalate_process

UID_STRING2=$(grep Uid: /proc/$PID/status)
PROC_UID2=$(echo "$UID_STRING2" | awk '{print $2}')

echo -e "UID before escalation: $PROC_UID\nUID after escalation:  $PROC_UID2"

# Exit with code 1 if before and after are the same
[ $PROC_UID -ne $PROC_UID2 ]
